### ISSUE TITLE
createViewModel and computed getters on model

### ISSUE THREAD

**Issue by mhluska** [mobxjs/mobx-utils#100]
It looks like the view-model created by `createViewModel` only inherits the obseravable and not the computed properties of the underlying model. Seems like a gotcha unless I'm missing something?

**Comment by mweststrate** [comment]
That is probably something that could be added with a little reflection indeed

**Comment by mweststrate** [comment]
PRs welcome

**Comment by carlosagsmendes** [comment]
Will this PR be merged soon?

**Comment by mweststrate** [comment]
merged & released as 5.0.0 (sorry it took so long, more maintainers for this package would be welcome :-))

**Comment by wrench7** [comment]
I'm having trouble getting computed properties of my model to be referenced in the viewModel.

Digging into the ViewModel code, `Object.getOwnPropertyNames(model).forEach` doesn't actually return computed getters, which means those keys never get added to the localComputedValues map.

Here's the model I'm using to pass into the createViewModel function (simplified to show the crux of my issue):

```
class SettingsModel {
    @observable regions: RegionVO[];
   
    constructor() {
        this.regions = RegionService.getRegions();
    }

    @computed
    get regionsLength(): number {
        return this.regions.length;
    }
}
```

Wondering if anyone else is using this util and successfully accessing computed getters from the ViewModel?

**Comment by kayakyakr** [comment]
@wrench7 can confirm that `getOwnPropertyNames(model)` does not pull computed properties off observables. Those are defined on `model.__proto__`.

@RafalFilipek I think to fix, might have to run the `isComputed` check against `model.__proto__` in a separate loop?

**Comment by wrench7** [comment]
@kayakyakr thanks for confirming. I looked at the code that was committed for this and the tests use `mobx.extendObservable` to create the observable. I'm using the `@observable` decorator in my code, so guessing that's why the tests didn't pick up the issue we're both seeing.
