### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by jimmycarry** [mobxjs/mobx-utils#102]
Does mobx-utils work perfect with mobx? Is mobx-utils **continually updated** when mobx update? I'll use mobx in my company project ,but I don't know mobx-utils permanence with mobx

**Comment by mweststrate** [comment]
It is updated when incompatibilities with latest MobX version arise

Op do 11 jan. 2018 om 11:59 schreef jimmy ye <notifications@github.com>:
