### ISSUE TITLE
enhance asyncAction with canceler function

### ISSUE THREAD

**Issue by ypwlal** [mobxjs/mobx-utils#104]
Refer to redux-saga, I would like to find a way to cancel actions' effects such as observable value changed after async function or entering *catch block code.*, especially for a singleton store in multiply components.

> The effects are mainly something will modify the observable value.

Like the concept of task in redux-saga, there will be two kinds of types actions: 
* ***takeEvery*** which means the async action can be called repeatedly at the same time. In this hand, the cancel function will cancel all the effects.
* ***takeLatest*** which means that when the action is called repeatedly， the prev call actions will be cancel automatically. The cancel function will cancel the latest call's effects. 

I would have the same usage likes *mobx-utils/asyncAction* but add a wrapper:
```javascript
   class Store {
       @observable loading = false;
       @observable text = 'nothing';
       @observable obj = {
            a: 1
       };
      @observable arr = [{ a: 2 }]

      @asyncActionWithCancel(cancel => this.cancelFetchData = cancel, 'takeEvery')
      *fetchData() {
            this.loading = true;
            try {
                const data = yield call('https://api.github.com', 'GET')  // mainly cancel in this timing
                this.loading = false;          // will not excute if cancel this action
                this.text = data.authorizations_url;   // will not excute
                this.obj.a++;   // will not excute
                this.arr[0].a++;   // will not excute
                alert(this.obj.a)   // will not excute
            } catch (e) {
                alert('error')    // will not excute
            }
      }
   }

  //component.js
  ...
  componentDidMount() {
    // for the type takeEvery, these three async action will be both effective，
    // for the type takeLatest, the last one will actually be effective.
    store.fetchData() 
    store.fetchData()
    store.fetchData()
 }
  componentWillMount() {
    // for takeEvery, this will cancel all the fetchData(); 
    //for takeLatest, this will cancel last one which is also the only one
    store.cancelFetchData() 
  }
  ...
```

1. The ***asyncActionWithCancel*** is a wrapper of original ***asyncAction***.
Its first arg is a function which will receive canceler.
Its second arg is the type of this action.('takeEvery', 'takeLatest')
 
2. Using the *generator.prototype.return* and some state is very easy to make it. In fact, in my private project, I would also wrap the ajax function after the keyword ***yield*** and inject the XmlHttpRequest Object into the cancel function which will abort the XmlHttpRequest in the same time.

ps: The cancel will only cancel the ineffective effects because there is no time travel to goback and therefore the developer need to initialize the state if used in a singleton store. 

It would be grateful if you are welcome my pr. lol

**Comment by mweststrate** [comment]
See #103, I think the idea is fine, basic support for cancel and generators has been made part of mobx in form of the `flow` api. Many further powerful patterns are possible, but I feel that would be better served in a dedicated package
