### ISSUE TITLE
Can't make test fail

### ISSUE THREAD

**Issue by minipai** [mobxjs/mobx-utils#106]
I was trying to work on #72, however I can't make test works(fail).

When I run `npm test`; there seems to have some problem while rollup compile `create-view-model.js`.
<img width="1012" alt="screen shot 2018-01-28 at 9 12 40 am" src="https://user-images.githubusercontent.com/239570/35476852-88699c6e-040b-11e8-8f43-3cd716734588.png">

The result is **✓ create view model** is always green. Even when I try to break it by make the syntax broken.

**Comment by mweststrate** [comment]
Just migrated the test suite to use `jest`. That should fix the issue. Hope it helps! If it causes new problems, feel free to reopen this issue.
