### ISSUE TITLE
Please consider exporting ViewModel

### ISSUE THREAD

**Issue by tylerjwatson** [mobxjs/mobx-utils#120]
Hi!

I need to subclass `ViewModel` to override `submit()`.  Currently my choices are implement `IViewModel<T>` with the same code, or replace the function on the created instance every time I get a new one out of the factory.

My use cases are this:

1. Allow for saving a view model back to a remote end (an async action) before submitting the changes back into a view model, and
2. Override the constructor to allow for `ObservableMap` instances to be handled as the observable for `model`: it would be cool to observe a map's changes event to add shadow getters and setters on the viewModel to entries in the map, and then `.merge` them back on submit, which it looks like it already does

Is this something you wonderful folks would welcome?  I've got two paths to go down here, if you're happy with the features I can simply PR the features, or PR the export.

Cheers!

**Comment by daedalus28** [comment]
Merged #125

**Comment by mweststrate** [comment]
Released as 4.0.1
