### ISSUE TITLE
Replicate old extendObservable fn

### ISSUE THREAD

**Issue by dubiousdavid** [mobxjs/mobx-utils#128]
We've seen a number of bugs related to the change of `extendObservable` after switching from Mobx 3 to 4. Might be nice to capture the behavior of the old `extendObservable` to ease the transition. Something like:

```javascript
let setObservable = (obj1, obj2) => {
  extendObservable(obj1, {})
  set(obj1, obj2)
}
```
Thoughts?

**Comment by daedalus28** [comment]
This seems like a good idea

**Comment by mweststrate** [comment]
What kind of bugs?

Op do 10 mei 2018 20:40 schreef Samuel Greene <notifications@github.com>:

**Comment by dubiousdavid** [comment]
Trying to set existing properties using `extendObservable`, or replacing `extendObservable` with `set` and trying to set properties on a non-observable object.

**Comment by mweststrate** [comment]
The behavior of `extendObservable` has been restored in MobX 4.15.2 / 5.15.2, so closing this issue.
