### ISSUE TITLE
createTransformer: need a way to give a debug name

### ISSUE THREAD

**Issue by vivainio** [mobxjs/mobx-utils#129]
We have several transformers. The drawback is that in mobx trace(), you don't see intelligible names for the transformation being triggered.

It would be useful to be able to give them a readable name.

**Comment by ItamarShDev** [comment]
I will have a look into it.
Hope to find my way though it :)

**Comment by ItamarShDev** [comment]
@mweststrate I can do this PR if some help could be supplied.
Kinda lost in the code :(

**Comment by ItamarShDev** [comment]
Cool. will look into it 
thanks @mweststrate

**Comment by vivainio** [comment]
This may be outdated now that createTransformer has been superceded by computedFn

**Comment by mweststrate** [comment]
...And it is merged anyway :)
