### ISSUE TITLE
keepAliveLazy

### ISSUE THREAD

**Issue by adamabeshouse** [mobxjs/mobx-utils#136]
I'm running into 2 major issues with the current keepAlive implementation:

(1) It prevents garbage disposal when there are no real references anymore (because its implementation using `.observe(()=>{})` creates a permanent reference)

(2) It causes reactive re-computation whenever the observable dependencies change, which is not necessary.

A version of this, "keepAliveLazy" maybe, which addresses these issues would be very useful

**Comment by adamabeshouse** [comment]
@mweststrate The difference is that I want it to stay cached outside the context of a reaction.

As I think about it more, I don't think it's possible to accomplish (1) without manual disposal, so I'll drop that need.

**Comment by mweststrate** [comment]
Right, so it stays alive, becomes dirty when it needs to be, but only recomputes when a consumer arrives? Take a look at `Reaction` in mobx, I think you could write such a thing

**Comment by mweststrate** [comment]
`observer` in mobx-react works a bit similar (although a bit noise source to read probably); it becomes dirty immediately, but doesn't recompute until the component is actual rendering (which is later in the future, depending on the scheduler of React itself)

**Comment by adamabeshouse** [comment]
@mweststrate the problem I'm running into is how do I register a functions observable dependencies to a reaction, so that it can set the dirty flag, without actually running the function in the reaction (because it should only run when a consumer requests it). Is there a way to do that in the mobX API?

**Comment by mweststrate** [comment]
@adamabeshouse could you open a PR with how for you got on the implementation and tests? That collaborates more easily :)

**Comment by urugator** [comment]
@adamabeshouse can you check whether https://github.com/mobxjs/mobx/pull/1799 solves the problem?

**Comment by adamabeshouse** [comment]
@urugator that looks quite perfect!! I knew there'd be a nice way to do it from the inside. thank you!
