### ISSUE TITLE
[Feature Request] Support for nested objects in ViewModel?

### ISSUE THREAD

**Issue by JabX** [mobxjs/mobx-utils#14]
I've read the source and I understand perfectly how it works and why nested objects aren't supported by `createViewModel`, but what would it take to add support for that?

I'm creating ViewModels for objects like this

``` ts
type DataEntry = {
    [key: string]: {
        $metadata; {}
        value: any
    }
} & {
    clear(): void
    set(data: {}): void
}
```

With `clear` setting all `value`s to `undefined` and `set` taking an object representing the data entry and setting all the corresponding `value`s.

Without support for nested objects I can't use either methods or set a `value` directly, with severely limits my use of the ViewModel.

I'm totally open to work on this myself, but I'd like to make sure that it makes sense and that it's doable before jumping in.

Thanks.

**Comment by mweststrate** [comment]
@JabX Would release #12 be sufficient, or do you also need nested objects?

**Comment by JabX** [comment]
Well, maps and arrays are an awesome addition (especially arrays, I am not that much into maps myself), but unfortunately that won't do anything to solve my problem.
Nested objects remain a top-priority feature for me, as I described in my exemple above.

I am a bit unsure about how it should be done though, either by somehow managing to make the current implementation recursive, or by simply managing a deep copy of the model observable and subscribing to it to update the viewmodel (which was the thing I as about to do before finding out `createViewModel`), but that seems pretty heavy.

**Comment by mweststrate** [comment]
recusive viewModels might be quite complicated. 

But depending if your data model is a tree, `const viewModel = observable(toJS/*or lodash.deepClone*/(model))` and on submit `lodash.deepMerge(model, viewModel)` might also already do the trick. But that doesn't give the benefits of this function (read original values until modified etc). 
Not really a solution within this model, but that might work as well for you

**Comment by JabX** [comment]
I fear that's only part of the solution, because I would also need to update the viewmodel when the model is changed. I don't even need the `submit()` part with that because when I submit my form I call a save service on the server that returns the new model and updates it.

Anyway I am going to build my own custom solution then, and you confirmed my suspicions about a recursive viewmodel.

**Comment by JabX** [comment]
This is the solution I came up with:
```ts
function createViewModel(model: DataEntry) {
    const getModel = () => toJS(model);
    const viewModel = observable(getModel());

    const reset = () => viewModel.set(toFlatValues(model));

    viewModel.reset = action(reset);
    viewModel.submit = action(() => _.merge(model, viewModel));
    viewModel.subscribe = () => {
        if (!viewModel.isSubscribed) {
            const disposer = autorun(reset);
            viewModel.unsubscribe = () => {
                disposer();
                viewModel.isSubscribed = false;
            };
            viewModel.isSubscribed = true;
        }
    };

    viewModel.subscribe();
    return viewModel;
}
```
`toFlatValues()` is a method I use to recursively transform my `{$metadata, value}` objects into `value`, just like `toJS()` does for observables.

The only pain point is that I kinda have to handle the model reactions manually, meaning that I have to call `unsubscribe()` before I destroy my viewModel (in `componentWillUnmount()` in my case). But this allows to control the interaction model -> viewModel, which might come handy someday.

**Comment by nidu** [comment]
@JabX do i understand correctly that your `createViewModel` is not general purpose? I guess for general purpose viewModel we also need dedicated classes for all types of observables?

**Comment by nidu** [comment]
@mweststrate i've made an attempt to support nested observable objects. The approach is far from ideal. Basically getter for property checks if returned value is observable object and wraps it with a view in this case. Submit and reset become recursive. Here is the code https://github.com/nidu/mobx-utils/commit/9b17503311a265986ae6313399d0e61b473798d1. What do you think of this? I support map and array support would be much harder.

**Comment by JabX** [comment]
@nidu Well, it could be made for a more general purpose, but it's a different, less efficient and harder to use solution that the original `createViewModel`.

**Comment by nidu** [comment]
@JabX i think most time this pattern is used for UI screens/forms where data volume is not that big so efficiency can be neglected here. At least for people who's ready to sacrifice some efficiency. Currently i ended by deep cloning nested collections on every change which is probably even less efficient and definitely takes more efforts.

**Comment by mweststrate** [comment]
@JabX @nidu thanks for your hard work! 

@nidu it seems you've take care of observable maps and arrays as well from your code? So it seems to be quite complete? Could you give me an overview of think that might be missing?

I also want to point you of a recent library built on top of MobX, still very much in progress, but it solves this problem as well: 

https://github.com/mobxjs/mobx-state-tree

With that you can do things like:

```
const todo = Todo({ completed: false})
const todo2 = clone(todo)
const patches = []
onPatch(todo2, p => patches.push(p))

//later, on "submit"
patches.forEach(p => applyPatch(todo, p))

// or alternatively, overwrite everything:
applySnapshot(todo, getSnapshot(todo2))
```

It still very much wip, but it solves the problem generically, granted that you build your state using a tree / factories. Would that solve your use cases as well? Note that it doesn't support the "reflect source values in clone as long as unmodified". So it is not entirely the same, but I am wondering whether this is a more simple approach that still serves the use cases?

**Comment by nidu** [comment]
@mweststrate no no, there's only support for objects and implementation implies you don't access unchanged observable object very often because of efficiency. 

Array and map support remained untouched. I think supporting map wouldn't be so hard (because there aren't so many methods, especially mutational ones), but to support an array quite a lot must be done. Array should return and store views for accessed elements which means we have a non contiguous array of views which we have to take in account in every array method. Eventually this means creating smth like ArrayView and MapView.

mobx-state-tree looks very nice! I'm gonna try to apply it in one of the cases. Actually i use one more `viewModel` layer which converts numbers to correct measurement system so i wrap `createViewModel` result with yet another wrapper, so i can't say easily if it will fit.

**Comment by dcworldwide** [comment]
I'm having the same need as well. Nit sure why recursing a object tree and creating view models per node wouldn't work?

**Comment by mweststrate** [comment]
I do see the use case for this feature, but I think mobx-state-tree will in the end provide a more generic solution to this problem. Therefor closing this issue for now.
