### ISSUE TITLE
Please export StreamListener<T>

### ISSUE THREAD

**Issue by thejohnfreeman** [mobxjs/mobx-utils#143]
`fromStream` returns `{ current: T, dispose(): void }`, which is awkward to type, so I create my own type alias for it, but would rather just import the right one from mobx-utils. I'd be happy to contribute this, but I have some questions.

`StreamListener` has some more stuff in it than just `current` and `dispose`, which themselves aren't even marked `public`.

1. Do you want me to separate `current` and `dispose` into their own interface?
2. Do you oppose me marking them `public`?

**Comment by mweststrate** [comment]
Public is the default in TS, PR exposing an interface is welcome!

Op za 18 aug. 2018 14:53 schreef John Freeman <notifications@github.com>:

**Comment by mweststrate** [comment]
Released as 5.0.2
