### ISSUE TITLE
Observable Query component

### ISSUE THREAD

**Issue by AjaxSolutions** [mobxjs/mobx-utils#146]
Could the fromPromise utility function be expressed as a React observable Query component?  This would be similar to the React Apollo Query component.

https://github.com/mobxjs/mobx-utils#frompromise
https://www.apollographql.com/docs/react/react-apollo-migration.html#query-component

**Comment by daedalus28** [comment]
This lib is only for mobx-utils, and not mobx-react utils. I've been thinking about creating one for mobx-react which would include things like this `Awaiter` component, which consume a `fromPromise` result:

https://github.com/smartprocure/contexture-react/blob/master/src/layout/Awaiter.js

If this would be helpful, I can set up a repo for it and publish it (along with a few other utils intended for use with mobx + mobx-react).

**Comment by mweststrate** [comment]
Sounds like a perfect case for a `mobx-react-utils` package indeed. Such initiative would be welcomed! In the mobx-react package there are several other ideas that would fit in there as well indeed.

**Comment by mweststrate** [comment]
@AjaxSolutions does a package like https://github.com/ghengeveld/react-async or https://github.com/capaj/react-promise in that case not basically solve the same problem? If the component is designed to handle promises through their lifecycles, is there still a need to make them observable?

**Comment by AjaxSolutions** [comment]
This was just an idea.  I don't have a problem if this idea is not implemented because there are other solutions already available.

**Comment by mweststrate** [comment]
Check! closing for now as the general goal seem to more declaratively render a promise, not necessarily an observable promise, and abstractions exist for the first one :-)

**Comment by daedalus28** [comment]
Just wanted to comment on this for future visitors. We originally invested in building our own `fromPromise` powered components like [`Awaiter`](https://github.com/smartprocure/contexture-react/blob/master/src/layout/Awaiter.js), but recently made the switch to go all in on `react-async` and recommend that to other people that stumble on this from google.

Here's our reasoning:
- As @mweststrate pointed out, this is a solved problem in the larger react community. `react-async` is well accepted and supported by the community.
- `react-async` will automatically be updated to use the upcoming suspense API to improve performance, which means we can just `npm install` and get on with our day.
- `fromPromise` requires knowing more things - it's not just a promise or an observable, it's a specific structure that we found isn't 100% intuitive for new devs. Moving to `react-async` noticeably reduced our developer on-boarding time. This shouldn't be underestimated - reducing the number of concepts you need to know is probably one of mobx's biggest strength over other alternatives (e.g. reducers and thunks and sagas and whatever else is currently in vogue).

Hopefully this comment is helpful to others - I know I'll be pointing our team members to it if it comes up again in the future 😄
