### ISSUE TITLE
'mobx' does not contain an export named '$mobx'.

### ISSUE THREAD

**Issue by LJJ1996** [mobxjs/mobx-utils#148]
./node_modules/mobx-utils/mobx-utils.module.js
173:26-31 'mobx' does not contain an export named '$mobx'.

"dependencies": {
    "mobx": "^5.1.0",
    "mobx-react": "^5.1.2",
    "mobx-react-devtools": "^5.0.1",
    "mobx-utils": "^5.0.2",
｝

**Comment by mweststrate** [comment]
"$mobx" is provided by both mobx 4 and 5, so should be available. Please
remove your node_modules to make sure no old dependencies are lingering
around. If that doesn't fix the problem, please create a minimal repository
demonstrating the problem

Op do 6 sep. 2018 om 09:30 schreef LJJ1996 <notifications@github.com>:

**Comment by msholty-fd** [comment]
@LJJ1996 I had this issue with mobx 4.3.0, but upgraded to 4.4.0 and the issue went away. Give that a try.
