### ISSUE TITLE
throttledValue

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx-utils#15]
http://codepen.io/jamiewinder/pen/kkLdGa?editors=1010

I found this quite useful. It's handy when you want an element of your state to be updated in a throttled manner, and want access to both the current and incoming values. For example, if you've got a text filtered list somewhere in your application, you can use the 'latest' value as your value (`<input value={a.latest} />`) and the `current` value as the actual value used (`.map(text => text.includes(a.current))`). 

I thought I'd float the idea and see what feedback I get. I can tidy this up and make a pull request if there is interest?

**Comment by mweststrate** [comment]
@jamiewinder that looks useful indeed! Feel free to create a PR :)

**Comment by jamiewinder** [comment]
Thanks, I'll do that. I'm curious to hear whether anyone thinks this could be better implemented, or can suggest better property names (`latest` and `current` are a bit misleading / somewhat synonymous).

**Comment by jamiewinder** [comment]
I've not looked into how feasible this is just yet, but an alternative could be to use something like `@computed` for throttling a value. Might be more flexible. For example, I tend to find a need for a 'throttled' value in filtered lists, but the filter tends to be made up of multiple parts. I use `@computed` to derive a predicate function from these parts. Therefore something like this might suit:

```
@observable filterText: string;
@observable filterGroupId: number;

@computedThrottled(500) get filterPredicate() {
    const { filterText, filterGroupId } = this;
    const upperText = filterText.toLocaleUpperCase();
    return (item) => (item.name.toLocaleUpperCase().includes(filterText) && item.groups.includes(filterGroupId));
}
```
i.e. Observe potentially multiple properties, but only update your value every 500ms. 

Thoughts?

**Comment by drslump** [comment]
IMHO unless there is some important performance reason I think it's best to have composable decorators. Here is a simple demo showcasing how to throttle and feed again the last result: https://jsbin.com/xiremoh/edit?js,output

**Comment by mweststrate** [comment]
@drslump this doesn't seem mobx specific, is there a general library that exposes these kind of primitives?

**Comment by drslump** [comment]
@mweststrate not that I'm aware of, at least on decorator form, there is `lodash` that offers some debouncing and throttling helpers. It'll be cool though! :)

Agree on this not being *mobx* specific, I haven't look into mobx internals but I assume it's probably cheap enough for mobx to trigger a *throttled* function on every *change*, since its computation will be memoized most of the time.

**Comment by mweststrate** [comment]
@jamiewinder I think actually the original example in your pen is already really useful. Still interested in making submitting that PR?

**Comment by jamiewinder** [comment]
Sure, I can do. Not convinced it's the best, or most flexible implementation but I haven't had much of a chance to try alternatives just yet. I'll see if I can put it together in the next couple of days. :)

**Comment by mweststrate** [comment]
Closing issue, see #24 instead
