### ISSUE TITLE
toStream doesn't seem to work with Maps

### ISSUE THREAD

**Issue by jamarzka** [mobxjs/mobx-utils#151]
Are Maps supposed to work with toStream? Am I doing something wrong? In the below example subscribe is never called.

https://codesandbox.io/s/7jyvo533n6
```
import { observable } from "mobx";
import { toStream } from "mobx-utils";
import { from } from "rxjs";

const x = new Map();
x.set("x", 3);
x.set("y", 2);

const m = observable(x);

const root = document.getElementById("root");

from(toStream(() => m)).subscribe(s => {
  // this is never called
  root.innerHTML += `<p>Stream changed: ${JSON.stringify(s)}</p>`;
});

root.innerHTML += `<p>Original x: ${JSON.stringify([...x])}</p>`;
root.innerHTML += `<p>Original m: ${JSON.stringify([...m])}</p>`;

x.set("x", 5);
m.set("y", 10);

m.set("new", 100);
x.set("new", 200);
```

**Comment by mweststrate** [comment]
Like `autorun` and `reaction`, `toJS` is a _tracking_ function, that means that it will track everything that is _read_ during the function execution. Your function doesn't ready anything (well, it does read `m`, but that is a `const` so it will never change).

Your function should derefernce what is supposed to be passed wonstream, for example `keys(m)` wil make it produce a value every time a key is added / removed. `m.toJS()` will shallowly clone and respond to all reads and writes to the map, and `toJS(m)` (admittingly a confusing name) will deeply visit the map `m` and hence track all changes in there. 

Understanding this is quite important to grokking the mental model of mobx, so best study https://mobx.js.org/best/react.html for some background!

**Comment by jamarzka** [comment]
Thanks! That all makes sense.
