### ISSUE TITLE
deepObserve with arrow function to also track reference changes

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-utils#157]
While deepObserve is really nice it would be awesome if it could have an override like
```
deepObserve(() => objArrayOrMap, (type, change) => {})
```
That way if it is not only the object that can change but also its reference it could automatically pick up the change rather than having to kill and recreate the deepObserve
The type sent in this change could be something like "rootChanged" or some such

**Comment by ItamarShDev** [comment]
so for my understanding, this is the line to start from? 
https://github.com/mobxjs/mobx-utils/blob/714024ab9edbce2b215e0de8f6f26e517f0db809/src/deepObserve.ts#L49

And evaluate the method here?
https://github.com/mobxjs/mobx-utils/blob/714024ab9edbce2b215e0de8f6f26e517f0db809/src/deepObserve.ts#L57 

Or am I totally misunderstanding the case?

**Comment by xaviergonz** [comment]
basically something like (untested)
```
deepObserveWithArrow(fn, listener) {
  let deepObsDisposer = deepObserve(fn(), listener);

  const reactionDisposer = reaction(fn, (newTarget) => {
    // target ref changed
    doDisposer();
    listener("rootRefChanged", undefined); // or the path to the root, whichever it usually is
    deepObsDisposer = deepObserve(newTarget, listener);
  });

  // return the disposer of it all
  return () => {
    deepObsDisposer ();
    reactionDisposer();
  };
}
```
but embedded into deepObserve itself (athough as a new function would be ok too I guess?)

**Comment by ItamarShDev** [comment]
Thanks!
Hope I'll find some time to dive into it myself

**Comment by mweststrate** [comment]
@xaviergonz why not just box the thing that might be changing?

E.g.
```javascript
let target = { something : true }
const boxed  = observable({ target })
deepObserve(boxed, () => {})
boxed.target = someNewTarget
```

**Comment by xaviergonz** [comment]
wait, what if the target is actually an external source? I'd need to synchronize the boxed value with the actual value with a reaction right?

**Comment by mweststrate** [comment]
if it is external, then it is probably a constant reference, and this whole
problem doesn't exist?

Op di 23 okt. 2018 om 17:15 schreef Javier Gonzalez <
notifications@github.com>:

**Comment by xaviergonz** [comment]
e.g. in a react component

interface SomeProps {
  someObject?: object;
}

deepObserve(() => this.props.someObject, ...)
vs... 
this.box = observable({target: this.props.someObject})
reaction(() => this.props.someObject, () => {this.box.target = this.props.someObject});
?

**Comment by xaviergonz** [comment]
I guess basically what I want is some kind of "deepReaction" for arrays, maps and objects without having to resort to tricks like 
```
reaction(() => array.slice(), ...
reaction(() => Object.entries(someMap), ...
reaction(() => Object.entries(someMap), ...
```
etc.
