### ISSUE TITLE
deepObserve missing from npm package

### ISSUE THREAD

**Issue by wbercx** [mobxjs/mobx-utils#158]
It appears that deepObserve is not actually included in what is currently published as version 5.0.3. I ran into this when trying to use deepObserve, but kept receiving errors saying `deepObserve is not a function`. It is nowhere to be found in `node_modules`.

It is also missing from the [README on npm for 5.0.3](https://www.npmjs.com/package/mobx-utils/v/5.0.3).

_Stylistic sidenote: `deepObserve.ts` seems to be the only camelcased file name in the repo._

**Comment by mrducnguyen** [comment]
I'm having the same issue. Trying to use `deepObserve` but it is not found in version 5.0.3

**Comment by mweststrate** [comment]
Apologies, bug in the publish script. Fixed in 5.0.4
