### ISSUE TITLE
proxy functions/computed on ViewModel

### ISSUE THREAD

**Issue by maxguzenski** [mobxjs/mobx-utils#16]
Is it possible to "bypass" functions from model, including computed and "get function()" ?  it looks like that for now it only proxy properties...

**Comment by mweststrate** [comment]
yes the idea is that you can do `viewModel.model.action()` etc, so my estimate was that that would be sufficient?

**Comment by maxguzenski** [comment]
Yes, I see that, but because my "obsessive-compulsive disorder" (is a joke), I would like to "free" my components from that. But its ok.
