### ISSUE TITLE
Please Support Weak Maps in createTransformer. So that object arguments can be cached as well, right now the only way to cache object arguments is by Stringifying them.

### ISSUE THREAD

**Issue by shubhang93** [mobxjs/mobx-utils#162]
Suppose I have transformer which transforms [{name:"ABC",age:24},{name:"XYZ",age:25}] into ["ABC==>24","XYZ==>25"], if the list changes at some point but retains most of its objects the cached values are recomputed as objects are compared by reference and not by identity. Right now I am stringifying each object but this is a cumbersome process and is not performant.

**Comment by ItamarShDev** [comment]
So as far as I understand it, your request is to support an array?

**Comment by shubhang93** [comment]
Nope not an array, but a way to cache results for object arguments, since most mmeoizing functions support this by using a weak map as a cache , which in turn gives us the ability to compare object arguments by identity not the content, even though my object contents are exactly the same the memozing function recomputes because the object reference has changed. createTransformer can take an optional resolver function with which we can decide how to resolve the cache.

**Comment by wbercx** [comment]
`createTransformer` already takes care of identity by [setting an auto-generated `$transformId`](https://github.com/mobxjs/mobx-utils/blob/master/src/create-transformer.ts#L64) on each object that gets passed in to the transformer. 

If a provided object already has a `$transformId`, it retrieves the cached computed value for it if there is one. This will happen as long as you keep passing the same object _instance_ to the transformer. 

````js
myTransformer([{name:"ABC",age:24}, {name:"XYZ",age:25}]); // Fresh array, fresh compute.
myTransformer([{name:"ABC",age:24}, {name:"XYZ",age:25}]); // Fresh array, fresh compute.

const myArgs = [{name:"ABC",age:24}, {name:"XYZ",age:25}];
myTransformer(myArgs); // Fresh array, fresh compute. 

// myArgs now has `myArgs.$transformId = 1`
myTransformer(myArgs); // Known array, returns cached computed for $transformId 1
````

Unless I'm missing something, a WeakMap would work the same way, the only difference being it wouldn't have to generate and set a transformId on each object that comes through. Happy to be corrected on this, as I haven't really used WeakMaps directly.

I do like the optional resolver function though. You'd still have to generate some sort of string that can be used as a cache key in the resolver, but it would also allow you to create a transformer that accepts more than one argument. 

But that last one could open you up to bugs that can be hard to track down. As always, with great power comes great responsibility. :smile:

**Comment by shubhang93** [comment]
Thanks a lot !
