### ISSUE TITLE
deepObserve does not work for boxed computed fields

### ISSUE THREAD

**Issue by rclai** [mobxjs/mobx-utils#168]
https://codesandbox.io/s/ywqqlv5znx

The example shows a regular `observe` properly triggering when the computation changes, but it does not trigger when observed using `deepObserve`

**Comment by ItamarShDev** [comment]
link broken @rclai

**Comment by mweststrate** [comment]
Computeds are indeed not respected by `deepObserve`. I think it would be awkward to support deepObserve on computed values, as it would be unclear what to observe, just the computed, like `observe`? Or would `deepObserve` mean that the _output_ of the computed would be deeply observed? That might have a lot of unwanted side effects though: First, everytime the output would change, the entire deepObserve tree would need to be tear down and set up for the new value. Secondly, views are often used to return specific parts of the tree. So recursing into the output of a computed value could easily result at best in observing changes twices, and worst, in unendless recursion. 

I propose a won't fix. Would be good to mention it in the documentation though.

**Comment by rclai** [comment]
Yeah, I was afraid that would be the case. I wouldn't want to pursue this further.
