### ISSUE TITLE
Add ability to get only the changed data in createViewModel

### ISSUE THREAD

**Issue by ItamarShDev** [mobxjs/mobx-utils#171]
Currently, according to docs, createViewModel has only `isPropertyDirty(propName)`

Is it possible to add an option to get _all changed props_ (hopefully with the data)

looking at https://github.com/mobxjs/mobx-utils/blob/c1d82ef88d0c2ee77f6a31e6dccde536c570fe44/src/create-view-model.ts#L65
we can just open an option to get `localValues` back.

**Comment by apsavin** [comment]
Looks like we need #173 if we want this to work correctly

**Comment by ItamarShDev** [comment]
@apsavin why? these two seems unrelated really, am I missing something?

**Comment by apsavin** [comment]
I suppose that a programmer would expect that changedValues contains only values that differ from model.

**Comment by ItamarShDev** [comment]
Oh, I see.
You are correct, will look into it

**Comment by ItamarShDev** [comment]
@apsavin added fix to PR :)

**Comment by apsavin** [comment]
LGTM, thanks!

**Comment by ItamarShDev** [comment]
fixed in #172 
closing

**Comment by mweststrate** [comment]
Released as 5.2.0
