### ISSUE TITLE
Using mobx.observe on a viewModel will cause Invariant failed errors

### ISSUE THREAD

**Issue by mattruby** [mobxjs/mobx-utils#18]
Here's a very simple fiddle showing the issue: https://jsfiddle.net/rubyred/t92nfs1r/2/

**Comment by mweststrate** [comment]
The reason for that is that `observe` is not supported on computed properties. I think that can actually be made to work, if you still need this, feel free to open an issue on mobx repo referring to this one

**Comment by mattruby** [comment]
Thanks for the clarification
