### ISSUE TITLE
Should changedValues be exposed in IViewModel<T>?

### ISSUE THREAD

**Issue by devuxer** [mobxjs/mobx-utils#180]
The docs state the `changedValues` is part of the API for view models, but in TypeScript, this is not accessible from `createViewModel(model).changedValues` because `changedValues` is not exposed in `IViewModel<T>`. If this is by design, the docs should be changed, otherwise, `changedValues` should be added to the interface.

**Comment by ItamarShDev** [comment]
Thank you very much!
Will look into it
