### ISSUE TITLE
QUESTION: createViewModel and updating property from class methods

### ISSUE THREAD

**Issue by lmgarret** [mobxjs/mobx-utils#183]
Hi! More of a question than an issue. I'm using `createViewModel` on a class instance and I'm trying to update a property (array) of this instance by calling one of its internal methods (which does array.push). After adding an element to this array property, the `viewModel` is not considered dirty and the UI does not resfresh.

Here is a simplified example of what I'm talking about: https://codesandbox.io/s/nk3x1n159m.
`MyObject` holds an array of items and a method to add to this array, `addItem`. Calling `addItem` does not trigger a UI refresh as it should do.

Any idea? Sorry if it has already been asked but I was not able to find a solution in the existing issues.

**Comment by mweststrate** [comment]
Using an arrow function binds the closure to a specific instance, so that  means that in the viewmodel, it is still bound to the original object. Using the following instead probably fixes the issue

```
  @action
  addItem(v) {
``
