### ISSUE TITLE
Terser/uglifyjs arrow fns

### ISSUE THREAD

**Issue by jeremy-coleman** [mobxjs/mobx-utils#194]
Hi, just wanted to mention there is a setting in minifiers that changes functions to arrows, could break the new computedFn and be hard to debug idk

**Comment by mweststrate** [comment]
I'm not fully grasping the above comment :). Could you elaborate / demonstrate / propose a fix?

**Comment by jeremy-coleman** [comment]
from the terser docs
https://github.com/terser-js/terser#minify-options

Compress options
arrows (default: true) -- Converts ()=>{return x} to ()=>x. Class and object literal methods will also be converted to arrow expressions if the resultant code is shorter: m(){return x} becomes m:()=>x.

fix (if an issue arises) would be to just add compress: {arrows: false} to terser options

**Comment by mweststrate** [comment]
I doubt this will be an issue, as it probably won't do so for things that depend on `this` or `arguments`, and without that, stuff shouldn't rely break. But alas, if a problem arises, this one can be reopened
