### ISSUE TITLE
moveItem from source to another source

### ISSUE THREAD

**Issue by crapthings** [mobxjs/mobx-utils#196]
i want to move b1 into a1 pos 2 so it becomes a1-3

```js
const data = observable([
  {
    _id: 'a1',
    label: 'a1',
    children: [
      {
        _id: 'a1-1',
        parentId: 'a1',
        label: 'a1-1',
        children: [],
      },

      {
        _id: 'a1-2',
        parentId: 'a1',
        label: 'a1-2',
        children: [],
      },
    ]
  },

  {
    _id: 'b1',
    label: 'b1',
    children: [],
  },

  {
    _id: 'c1',
    label: 'c1',
    children: [],
  },
])
```

**Comment by mweststrate** [comment]
Don't get what the question is here (as in, how does this relate to mobx or mobx-utils). But `data[0].children.push(...data.children.splice(1,1))` should do the trick?

**Comment by crapthings** [comment]
ah i mean this api

https://github.com/mobxjs/mobx-utils#moveitem

just want a utils that can move things between mobx tree.

https://github.com/rhalff/dot-object#move-a-property-within-one-object-to-another-location


i'm thinking how to combine these two works, but thanks anyway~

mobx rulez~
