### ISSUE TITLE
moveItem not compatible with mobx-state-tree array of references

### ISSUE THREAD

**Issue by davidosomething** [mobxjs/mobx-utils#197]
demo: https://infallible-clarke-6034d9.netlify.com/ -- just hit swap
code: https://github.com/davidosomething/mst-dead-demo/blob/master/src/App.js#L26

dev error: 
![image](https://user-images.githubusercontent.com/609213/57173988-5ca94600-6e05-11e9-85eb-0b5f49e892e7.png)

**Comment by mweststrate** [comment]
Correct, but `moveItem` is basically still here for legacy purposes, and I recommend to not combine it with MST.
