### ISSUE TITLE
suggestion: add fromPromise function for hooks (useObservablePromise?)

### ISSUE THREAD

**Issue by phiresky** [mobxjs/mobx-utils#202]
might look like this:

```
function usePromise<T>(factory: () => Promise<T>) {
	return useMemo(() => fromPromise(factory()), [])
}
```

**Comment by mweststrate** [comment]
This library doesn't rely on React, so it doesn't really fit, but feel free to add it as suggestion to the readme.

**Comment by phiresky** [comment]
That makes sense. Maybe in the future a mobx-react-utils library would be useful.

> feel free to add it as suggestion to the readme.

To be honest I don't feel confident enough if the above is the right approach (useMemo vs useEffect etc), and also it might need some logic regarding caching or observables the promise itself depends on.
