### ISSUE TITLE
createViewModel with array

### ISSUE THREAD

**Issue by samr28** [mobxjs/mobx-utils#209]
I'm trying to use `createViewModel` to make a viewModel of an object with an array. When I edit the array property of the viewModel, the changes are immediately reflected on the original object. Not sure if this is a bug or if I'm using this wrong. Help would be much appreciated!

```js
import { observable } from "mobx";
import { createViewModel } from "mobx-utils";

class AppState {
  @observable user = {
    arr: [1]
  };
}

const appState = new AppState();
const userState = createViewModel(appState.user);

console.log(appState.user.arr[0]);  // 1
console.log(userState.arr[0]);  // 1

userState.arr[0] = 5;

// User.arr[0] should still be 1
console.log(appState.user.arr[0]);  // 5
console.log(userState.arr[0]);  // 5
```
https://codesandbox.io/s/minimal-mobx-react-project-6hthy

**Comment by FredyC** [comment]
And when would expect the value change would happen? MobX is not asynchronous, it does the change right away. What would be even use case where you need to see old values after changing it? :)

**Comment by samr28** [comment]
My understanding is that the viewModel will not update the original model until `viewModel.submit()` is called. This seems to be how it works with regular variables. Based on this: https://github.com/mobxjs/mobx-utils/issues/170, I'm assuming that it does a deep copy which would allow arrays and objects to work as I have described above but it must be just doing a shallow copy.

**Comment by FredyC** [comment]
Sorry, I am not familiar with this particular utility. By reading docs, it indeed should behave the way you are saying. Probably best if someone else who knows about it can have a look.

ping @ItamarShDev (you did some changes to it a while ago)

**Comment by ItamarShDev** [comment]
@FredyC @samr28 
Thank you! looking into the source.
Sorry for not being available lately

**Comment by ItamarShDev** [comment]
see the docs: 

>   You may use observable arrays, maps and objects with createViewModel but **keep in mind to assign fresh instances of those to the viewmodel's properties, otherwise you would end up modifying the properties of the original model.** 

see the [right approach](https://codesandbox.io/s/minimal-mobx-react-project-6hthy?fontsize=14)

BTW, please compare changes in create-view-model between `userState` and `userState.model`
as the docs show.

**Comment by designbyadrian** [comment]
> @samr28
> see the docs:
> 
> > You may use observable arrays, maps and objects with createViewModel but **keep in mind to assign fresh instances of those to the viewmodel's properties, otherwise you would end up modifying the properties of the original model.**
> 
> see the [right approach](https://codesandbox.io/s/minimal-mobx-react-project-6hthy?fontsize=14)
> 
> BTW, please compare changes in create-view-model between `userState` and `userState.model`
> as the docs show.

There is no reference to viewModel in the linked CodeSandbox example.

**Comment by EmilHelle** [comment]
Does anyone have a solution or an example of the correct approach to solve this? I have been trying for some time to do changes on arrays of objects in many different ways, and they only submit the changes immediately to the target model. The description in the docs was a bit vague too.
