### ISSUE TITLE
fromPromise: Best practice on where and how to use it

### ISSUE THREAD

**Issue by feedm3** [mobxjs/mobx-utils#211]
To show the different states of an asynchronous fetch, I'm using the `fromPromise` helper method. I'm using it by returning it from the stores fetch method like this:

```
export class ItemStore {
  @observable
  public items: string[] = [];

  @action
  public fetchItems(): IPromiseBasedObservable<void> {
    return fromPromise(
      new Promise(resolve => {
        setTimeout(() => {
          runInAction(
            (): void => {
              this.items.push("test 1", "test 2");
            }
          );
          resolve();
        }, 3000);
      })
    );
  }
}
```

In the component I can now use the return object from `fromPromise` to differntiate the states without any more boilerplate:

```
const itemStore = new ItemStore();

@observer
export default class Items extends React.PureComponent {
  private fetchItems?: IPromiseBasedObservable<void>;

  public componentWillMount(): void {
    this.fetchItems = itemStore.fetchItems();
  }

  public render() {
    if (!this.fetchItems) {
      return null;
    }

    return this.fetchItems.case({
      pending: (): JSX.Element => <div>loading items...</div>,
      fulfilled: (): JSX.Element => (
        <ul>
          Items:{" "}
          {itemStore.items.map(item => (
            <li>{item}</li>
          ))}
        </ul>
      ),
      rejected: (): JSX.Element => (
        <div>couldn't load items. please try again later...</div>
      )
    });
  }
}
```

The problem here is: `componentWillMount` is deprectad and also fetching should be done in `componentDidMount`. But if I put the assignment from the `.fetchItems` into `componentDidMount`, the rerendring will not be triggered anymore on changes.

My Question now: 
- Am I using `fromPromise` correct? For me, putting it into the store looks like best place, especilly when multiple components need to track the current fetch state (I don't want to use `fromPromise` in every component seperately).
- Is the assignment of the `fromPromise` object in the component a good idea? If yes, where exactly?

You can checkout here to see everything in action: https://codesandbox.io/embed/mobx-utils-frompromise-best-practice-0lzmb

**Comment by ItamarShDev** [comment]
see https://mobx.js.org/best/pitfalls.html section **Don't copy observables properties and store them locally** please

**Comment by ItamarShDev** [comment]
to make it similar to your code look [here](https://github.com/mobxjs/mobx-utils#examples)
you just need an observable to assign the result to
