### ISSUE TITLE
IPromiseBasedObservable defaults to observable deep false

### ISSUE THREAD

**Issue by Strydom** [mobxjs/mobx-utils#219]
When using `@observable public nodeSets: IPromiseBasedObservable<FolderItem[]>;` I found that when trying to modify `nodeSets.value`, it did not trigger re-renders.

I think it's because of this line here:
https://github.com/mobxjs/mobx-utils/blob/master/src/from-promise.ts#L88

Is this behaviour expected or should you be able to update the value and have it trigger re-renders?

From the description it sounds like the value should be observable and I expect it to react to changes to its "deeper" properties.

I'm trying to update the `tags` in a `FolderItem` and have it re-render a Table to show the new `tags` value. 

```
export interface FolderItem {
  id: number;
  type: string;
  title: string;
  authorName: string;
  parent?: number;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
  selected?: boolean;
}
```

**Comment by urugator** [comment]
It's by design (see #54). You can make the value observable yourself `.then(val => observable(val))`

**Comment by mweststrate** [comment]
Having a promise as owner of state that is going to be modified in the future is a very confusing model in the long term and confusing responsibility. IF you are going to modify the output of some data fetching process, it will be a lot clearer if there is an explicit place where you store that state, merge the result of the process in there, and in that place probably also organize how changes are propagated back to the server etc etc
