### ISSUE TITLE
queueProcessor debounce not working as expected

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx-utils#22]
Perhaps I'm misunderstanding, but shouldn't this print the 1, 2, then 3 in sequence with a 3-second in between each? 
http://codepen.io/jamiewinder/pen/qqdgBN?editors=1010

It actually just waits three seconds then processes all three at once.

**Comment by mweststrate** [comment]
No, it fires the processor, then queues up for 3 seconds, then fires again.

But I think your use case might actually be more useful :)

Interested in making a PR?

**Comment by mweststrate** [comment]
Closed for inactivity
