### ISSUE TITLE
Release for 5.5.1

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-utils#222]
Could anybody release v5.5.1? I just did commits to prepare for it until I realized I don't have permissions to do npm publish for this repo :(

@mweststrate

**Comment by mweststrate** [comment]
Granted permission to publish :)

**Comment by xaviergonz** [comment]
Thanks! published!

**Comment by blacksteed232** [comment]
@xaviergonz wait, I just updated to 5.5.1 but I still get error when I dont use await inside actionAsync though. Also did you tag 5.5.1 for this repo?

**Comment by xaviergonz** [comment]
Just pushed the tag (I forgot it), also checked that the bundle on npm contains the changes.

Could you create a reproduction case? maybe you are using await task inside async function that is not marked with asyncAction?

**Comment by xaviergonz** [comment]
Btw, if you are using the new version then the error message should be slightly different (should include if the error happened inside task or when the action is finishing, and if the action is finishing which is the action name that failed.

**Comment by blacksteed232** [comment]
@xaviergonz my bad! I installed but did not rerun webpack so the changes didnt kick in! Thank you so much!
