### ISSUE TITLE
I  just wonder how you generate ts declaration file

### ISSUE THREAD

**Issue by kwzm** [mobxjs/mobx-utils#227]
This is not a issue, I am writting my own npm library by typescript, and I referred to your library, I have a problem when I want to generate a declaration file.
I see `"typings": "lib/mobx-utils.d.ts",` in package.json, but I don't know how it generated.

**Comment by mweststrate** [comment]
Enable the `declaration` option in your compiler settings.

**Comment by kwzm** [comment]
@mweststrate Thanks, but I didn't find where you enable this option, I found tsconfg.json and npm srcipt.

**Comment by mweststrate** [comment]
might be implicitly on. Anyway, it's a compiler option. I assume you can
google your way from here :)

**Comment by kwzm** [comment]
@mweststrate Ok, thanks a lot!
