### ISSUE TITLE
'actionAsync' context not present when running 'task' only in React Native projects

### ISSUE THREAD

**Issue by jpgarcia** [mobxjs/mobx-utils#243]
Hi guys,

I was troubleshooting this error in a **React Native** application and found the https://github.com/mobxjs/mobx-utils/pull/240 which apparently fixes the issue https://github.com/mobxjs/mobx-utils/issues/239 in **5.5.4** so I upgraded the library in my **React Native** but it didn't work

In order to check the fix was actually working I tried by creating a simple console application and it worked! 

So I created a React Native app from the scratch and I faced the same issue

# Repro Steps

Creete a new React Native app

```bash
npx react-native init actionasync
cd "actionasync"
npm i mobx mobx-utils
```
run the app:
```bash
npx react-native run-ios
```

Replace the **index.js** file with the following contents

```js
/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

import {task, actionAsync} from 'mobx-utils';

const r = new Promise(resolve => {
  setTimeout(() => {
    resolve(null);
  }, 1000);
});

const actionAsync1 = actionAsync('actionAsync1', async () => {
  await task(r);
});

const actionAsync2 = actionAsync('actionAsync2', async () => {
  await task(r);
});

actionAsync1();
actionAsync2();

AppRegistry.registerComponent(appName, () => App);

```
After that the app will refresh and you will see the unhandled rejection warning as depicted below

![image](https://user-images.githubusercontent.com/95109/78147480-f3152b80-7409-11ea-9bc3-017022be7b96.png)

> Error: [mobx-utils] invalid 'actionAsync' context when finishing action 'actionAsync1'. an action context for 'actionAsync2' was found instead. did you await inside an 'actionAsync' without using 'task(promise)'? did you forget to a

**Comment by jpgarcia** [comment]
More info:

Not sure why but if I change https://github.com/mobxjs/mobx-utils/blob/master/src/action-async.ts#L19

```js
let taskOrderPromise = Promise.resolve()
``

**Comment by jpgarcia** [comment]
I will close this as I experienced the same issue in older versions of node. So I will leave a comment on #239 suggesting to reopen the issue

**Comment by xaviergonz** [comment]
Hi, in which version of node where you able to reproduce it?

**Comment by jpgarcia** [comment]
Hi @xaviergonz I just updated the previous issue with more info https://github.com/mobxjs/mobx-utils/issues/239#issuecomment-609052746 Thanks!
