### ISSUE TITLE
Bug in lazyObservable pending state

### ISSUE THREAD

**Issue by singggum3b** [mobxjs/mobx-utils#249]
https://github.com/mobxjs/mobx-utils/blob/4b5964042f72c7a26526d36d4365d191904cb64d/src/lazy-observable.ts#L56

**Comment by singggum3b** [comment]
> https://github.com/mobxjs/mobx-utils/blob/4b5964042f72c7a26526d36d4365d191904cb64d/src/lazy-observable.ts#L56

I think this should be wrap in `allowStateChanges` no ?
Its causing issue when there're observer on `pending`

**Comment by mweststrate** [comment]
I think you are correct! Interested in submitting a PR with fix and a unit test demonstrating the old issue, so that we won't regress in the future?

**Comment by singggum3b** [comment]
> I think you are correct! Interested in submitting a PR with fix and a unit test demonstrating the old issue, so that we won't regress in the future?

Sorry for late reply. i was going to do it in monday but look like @NaridaL was way faster 👍
