### ISSUE TITLE
Refreshing a lazyObservable forces it to load a value

### ISSUE THREAD

**Issue by DylanMcCall** [mobxjs/mobx-utils#25]
I am using `lazyObservable` along with `autorun` to keep track of fields from a Dexie database. (Not 100% sure if this is a sane approach as I'm new to MobX, so feel free to tell me if I'm doing it wrong).

Here's how that looks:

    export class ObservableDexieTable {
        @observable ready = false;

        tableLazyFields = {
            count: () => this.table.count()
        }

        constructor(observableDexie, tableName) {
            this._observableDexie = observableDexie;
            this.tableName = tableName;

            for (const [field, callback] of Object.entries(this.tableLazyFields)) {
                this[field] = lazyObservable(
                    sink => callback().then(result => {
                        console.log("Load field", this.tableName, field, this[field]);
                        return sink(result);
                    })
                );
            }

            autorun(
                this.table;
                untracked(() => {
                    for (const field of Object.keys(this.tableLazyFields)) {
                        this[field].refresh();
                    }
                });
            );
        }

        get db() {
            return this._observableDexie.db;
        }

        get table() {
            return this._observableDexie.table(this.tableName);
        }
    }

So, we have a bunch of lazy-loading fields, and we trigger refresh() on them whenever the database changes, to keep their values up to date. (observableDexieTable is another class that uses "dexie-observable" and an atom that fires whenever the database changes).

So lazyObservable works great and our fields aren't loaded until we access them, *except* when I include that autorun code. As soon as I add that, the field's fetch callback runs immediately, no matter what! I was instead expecting the observable to only run fetch if it is being observed.

**Comment by mattruby** [comment]
autorun will fire initally to see what it needs to observe. I think you'd
be better off using reaction. That will not fire initally by default.

**Comment by DylanMcCall** [comment]
Thanks for the suggestion :) I would *love* to use reaction. Alas, that (and observe) weren't cooperating for me. Not exactly sure why, but possibly because the value of the observable stays the same? Probably just need to dig a little deeper to figure out what field to attach to with my reaction. For working with Dexie I've got something very much like the Clock example for atoms: http://mobxjs.github.io/mobx/refguide/extending.html.

(Dexie is a handy library for accessing IndexedDb, by the way - the database is a simple object with a bunch of functions that return promises. It's sort of mutable, but of course its state doesn't necessarily reflect the data we're interested in).

Still, what I'm hoping to achieve here is to tell those lazyObservables they need to be loaded again, but not actually load them if they're unused. (So that initial autoRun shouldn't really do anything). I might be fixing the wrong thing here, but I've had a happy result so far hacking together my own lazyObservable with a new "softRefresh" function. Awkwardly named, and rather redundant, but I guess it would be silly to break backwards compatibility:

    export function lazyObservable<T>(
        fetch: (sink: (newValue: T) => void) => void,
        initialValue: T = undefined,
        modifier = IDENTITY
    ): {
        current(): T,
        refresh(): T
    } {
        let started = false;
        const value = observable(modifier(initialValue));
        let currentFnc = () => {
            if (!started) {
                started = true;
                fetch(action("lazyObservable-fetch", (newValue: T) => {
                    value.set(newValue);
                }));
            }
            return value.get();
        };
        return {
            current: currentFnc,
            refresh: () => {
                started = false;
                return currentFnc();
            },
            softRefresh: () => {
                if (started) {
                    started = false;
                    return currentFnc();
                } else {
                    return value.get();
                }
            }
        };
    }

**Comment by mweststrate** [comment]
@DylanMcCall I think actually you are right, `refresh` should not do anything if the observable isn't fetched yet. I think that would be the expected behavior of `refresh` in any case? Would you be interested in making a PR with this new `refresh` behavior, with an optional (`force` behavior to get the old behavior?)

**Comment by mweststrate** [comment]
Fix has been released in 2.0.1

**Comment by DylanMcCall** [comment]
Ah, perfect! Sorry I went and disappeared into oblivion with this one. I had "send PR to mobx-utils" at the top of my todo list then it all got bogged down with school. Alas. Thanks for making this cool thing :)
