### ISSUE TITLE
Hitting error when trying to createViewModel on observable array

### ISSUE THREAD

**Issue by ronyong91** [mobxjs/mobx-utils#266]
I'm getting error Error: [mobx-utils] createViewModel expects an observable object when i am trying to create view model on observable array. Example :

@observable treatments : Treatment[] = [];
treatmentDet = createViewModel(this.treatments);

**Comment by mweststrate** [comment]
That function works with objects, not arrays (at the root)

**Comment by ronyong91** [comment]
Alright then. I am cloning the observable array and after i done all the necessary stuffs , i just assign it back to the array, sort of like submit. Just a workaround. Closing the issue , thanks man.
