### ISSUE TITLE
Enhancement - ObservableGroupMap shallow option

### ISSUE THREAD

**Issue by ProTip** [mobxjs/mobx-utils#269]
If I'm not mistaken it appears that the observable array creation is the deep default. I'm interested in being able to group items into shallow observable arrays. I would like to propose extending the options of the ObservableGroupMap to allow for shallow array creation.

**Comment by NaridaL** [comment]
There's only one observable array as far as I'm aware. What behavior are you observing? I assume you have some reactive behavior on one of the group arrays. This will react to changes to objects in the arrays not because it is a "deep observable" array, but because the properties of of the contained items are themselves observable.

**Comment by ProTip** [comment]
Yes, items added to the group array are being converted to and stored as proxy objects.

The `observable` "decorator" is being used to create the group arrays here: https://github.com/mobxjs/mobx-utils/blob/master/src/ObservableGroupMap.ts#L151

Observable is an "alias" to `observable.deep` per the Mobx documentation and recursively calls `observable` on items added to collections: https://mobx.js.org/refguide/modifiers.html#deep-observability

This can be overridden by setting the deep option: `observable([], {deep:false}`

**Comment by NaridaL** [comment]
@ProTip Looks like I missed that. This definitely makes sense. I'd change it to always have the group arrays be shallow. Or do we need an option for this? If the base array is deep observable, then it makes no difference, and I can't image a scenario where you want the base array to be shallow but the group arrays to be deep.
