### ISSUE TITLE
Create "memoize" helper

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx-utils#27]
As for now, mobx has `computed` decorators, which could be used on argumentless functions. It would be useful to create "memoize" helper, which acts like [lodash memoize function](https://lodash.com/docs/4.17.2#memoize), but with usage of mobx power.

**Comment by mweststrate** [comment]
Closed for inactivity. The main reason why such a think is not build in, is that it is hard to prevent the memoization table from growing indefinitely.
