### ISSUE TITLE
now() returns an old timestamp when resubscribing to an inactive ticker

### ISSUE THREAD

**Issue by Phault** [mobxjs/mobx-utils#271]
Currently if a ticker for a given interval (say 1000) goes inactive due to lack of subscribers, it's latest value will be returned initially when you resubscribe. So for instance if it reported 3000 before going inactive, then 5 seconds pass and you call now(1000). Instead of returning 8000 it would report 3000. A second later it will then report the correct value of 9000.

[Here's a codesandbox to demonstrate](https://codesandbox.io/s/mobx-utils-now-bug-1e9xg?file=/src/index.js). After 3 seconds the now() call tells us no time has elapsed yet.

**Comment by mweststrate** [comment]
Released as 6.0.0, closing
