### ISSUE TITLE
fromStream is broken

### ISSUE THREAD

**Issue by varog-norman** [mobxjs/mobx-utils#279]
Looks like `fromStream` doesn't work at 6.* version 

<img width="1226" alt="1" src="https://i.imgur.com/5w9jcRh.png">

But in previous version 5.* everything's good
<img width="1221" alt="2" src="https://i.imgur.com/lFAAAbS.png">

**Comment by mweststrate** [comment]
Did you follow the mobx migration guide? Please provide a sandbox
reproduction.

Op vr 2 okt. 2020 19:13 schreef Varog <notifications@github.com>:

**Comment by varog-norman** [comment]
Yep, tried to do everything from migration guide. Here is the sandbox example https://codesandbox.io/s/hardcore-snyder-nin76

**Comment by mweststrate** [comment]
Thanks for reporting! There was a build issue causing incorrectly compiled code to end up in the bundle. Should be fixed in 6.0.1!
