### ISSUE TITLE
actionAsync - what happened?

### ISSUE THREAD

**Issue by asfernandes** [mobxjs/mobx-utils#282]
AFAIK this function was present in v5 but it's not in v6 anymore.

I din't found an issue about deprecation or removal.

**Comment by mweststrate** [comment]
Iirc it is deprecated in favor of MobX's flow

**Comment by asfernandes** [comment]
Does it have a good reason for? Not everyone wants to use generator, and types does not work great in TypeScript.

**Comment by mweststrate** [comment]
Yes, not interested in maintaining 3 alternatives to achieve a similar thing

**Comment by asfernandes** [comment]
Fortunately I haven't the time to install mobx-utils before, when I saw the nicely `actionAsync`.

And if the library has this policy of remove things even without notice, I will not use it.
