### ISSUE TITLE
Passing equals option to computedFn does not change behaviour

### ISSUE THREAD

**Issue by DavidCasillasRivero** [mobxjs/mobx-utils#292]
I'm trying to pass an `options` object to `computedFn()` with the `equals`  property to set the `comparer` function to use.

```
filterForIndividual = computedFn(function(individualsId) {
    return this.filter((id, item) => ThObj.value(item, ThIdSessions.INDIVIDUALS_ID) === individualsId);
}, { equals: comparer.structural, });
```

The problem is that it always uses the `comparer.default` comparer. I have set a debug point in `mobx.comparer.ts` file and it never enters in the `structuralComparer()` method and always use `defaultComparer()`. 

I have tried to simplify the real code in a CodeSandbox and try to understand what is happening. The problem can be reproduced, no matter what the `comparer` value you set, the `computedFn()` always runs - so it is not caching - even if the returned data is the same (not same reference).

https://codesandbox.io/s/pedantic-yonath-owtvt?file=/src/App.js

Inspecting the source code seems that `computedFn()` can accept an `options` object and pass it throught to `computed()`, so there must be something I am missing .

**Comment by urugator** [comment]
Btw in sandbox you have a typo `{ equal: comparer.structural }`

**Comment by mweststrate** [comment]
In my phone, so apologies, didn't check the sandbox, but is the computed
observed? If it is not kept alive it won't cache nor compare.

**Comment by DavidCasillasRivero** [comment]
@urugator Thanks, you are right, I fixed it to `{ equals: comparer.structural }` and also change the `{ equals: comparer.identity }` but nothing is changing.
@mweststrate I think it is, the computed is used inside a component enclosed in `observer` if you mean that.

**Comment by urugator** [comment]
> "Check the console the see if the computedFn() is being called or cached."

The `computedFn` must always run on, otherwise it has nothing to compare. Comparer should prevent the observer from re-rendering, not from recomputation.

**Comment by urugator** [comment]
Try: 
```javascript
const t = new Test();

autorun(() => {
  console.log("autorun");  
  const map = t.filterStructural()  
})

t.increment();
t.increment();
t.increment();
```
There is just a single "autorun" in console as opposed to using `t.filterIdentity` (4).

**Comment by DavidCasillasRivero** [comment]
Of course, you are right, I had this sentence from MobX and completely misunderstood it. 

> "Computed values can be used to derive information from other observables. They evaluate lazily, caching their output and only recomputing if one of the underlying observables has changed. If they are not observed by anything, they suspend entirely."

I updated the codesandbox and the re-render only happens using `comparer.identity` as expected.

So the problem in my original code must be somewhere else, and the options passed to `computedFn`  are working. Thanks for the super fast response.
