### ISSUE TITLE
createViewModel from ObservableMap

### ISSUE THREAD

**Issue by BarryThePenguin** [mobxjs/mobx-utils#30]
Is it possible to use createViewModel from an ObservableMap?

I'm seeing `Uncaught Error: [mobx-utils] createViewModel expects an observable object`.

In the [`submit` action](https://github.com/mobxjs/mobx-utils/blob/b9b35875b25c81073c9483476ebc054f12e13755/src/create-view-model.ts#L47-L61) there's an `isObservableArray` and `isObservableMap` check which then calls `replace`, or `clear` and `merge`, on the `destination`. But I don't think they will be used because of the `invariant` check in the constructor only checks for `isObservableObject`.

**Comment by BarryThePenguin** [comment]
Looking into it more, I don't think my understanding above is correct..

**Comment by dgdosen** [comment]
I've got this same issue - I can't use createViewModel on an observable array....

**Comment by hyusetiawan** [comment]
I am having the same issue as well, cannot create a view model on an observable array
