### ISSUE TITLE
Testing stuff using now() leads to tests that are failing for wrong reason

### ISSUE THREAD

**Issue by jansav** [mobxjs/mobx-utils#306]
> Multiple clocks with the same interval will automatically be synchronized.

The fact that timers are synchronized, will make multiple unit tests share state between them.

**Here is unit test that will reproduce the issue:**

Notice how latter test will fail, even though it shouldn't.  If you run either of tests individually, the test will pass. 

```typescript
import { now } from "mobx-utils";
import { computed, observe } from "mobx";

describe("now", () => {
  let actual: boolean;

  beforeEach(() => {
    jest.useFakeTimers();

    jest.setSystemTime(new Date("2015-10-21T07:28:00Z"));

    const someComputed = computed(() => {
      const currentTimestamp = now(1000);

      return currentTimestamp > new Date("2015-10-21T07:28:00Z").getTime();
    });

    observe(someComputed, (changed) => {
      actual = changed.newValue as boolean;
    }, true);
  });

  it("given time passes, works", () => {
    jest.advanceTimersByTime(1000);

    expect(actual).toBe(true);
  });

  it("does not share the state from previous test", () => {
    expect(actual).toBe(false);
  });
})
```

And to be absolutely sure that synchronization is causing the trouble, you can comment out stuff from implementation of `now` to see that both unit tests will pass at same time when synchronization is disabled.

```typescript
    function now(interval) {
      if (interval === void 0) { interval = 1000; }
        if (!mobx._isComputingDerivation()) {
            // See #40
            return Date.now();
        }
        // if (!tickers[interval]) {
            if (typeof interval === "number")
                return createIntervalTicker(interval).current(); // Notice return here
            else
                tickers[interval] = createAnimationFrameTicker();
        // }
        // return tickers[interval].current();
    }

```

I'd like to be able to disable the synchronization in unit tests.

**Comment by NaridaL** [comment]
Sorry for the long delay, I don't do much with JS/TS these days.

I don't quite understand what the expectation is, of what is supposed to set "actual" back to false after the first test, as it is a shared variable. Ie if I have the following dummy test, it also fails.


```
describe("now22", () => {
    let actual
    let setTrue

    console.log("describe (only gets called once)")

    beforeEach(() => {

        // actual = false
        setTrue = function () { actual = true }

    });

    it("given time passes, works", () => {
        setTrue()

        expect(actual).toBe(true);
    });

    it("does not share the state from previous test", () => {
        expect(actual).toBe(false);
    });
})
```

**Comment by Nokel81** [comment]
Your test case is slightly different, in the initial post it is not that the value gets "reset back to false" but that in both cases the autorun assigns to `false` but in the first test it then also gets assigned to `true`

**Comment by NaridaL** [comment]
Hmm, that makes sense. See other comments on PR then.

**Comment by NaridaL** [comment]
This approach seems much simpler.

I've made a couple of minor improvements: renamed it to `resetNowInternalState` (because the relation to now is currently not visible, and we don't use the "timers" terminology anywhere; and added documentation comments.
