### ISSUE TITLE
ObservableGroupMap for Map to Arrays

### ISSUE THREAD

**Issue by BrianHung** [mobxjs/mobx-utils#314]
I'm currently using mobx-state-tree and have a map of objects that look like

```ts
const Cell = {
  id: uuid,
  colId: uuid,
  rowId: uuid
}

const cells = observable.map({...});
```

I would like to create arrays that effectively index on `colId` and `rowId` and which are cached as long as the entries remain the same.

```ts
const getRowCells = (rowId) => values(cells).filter(cell => cell.rowId === rowId)
```

I'm running into an performance issues with mobx-state-tree (https://github.com/mobxjs/mobx-state-tree/discussions/1994) where arrays are not cached since MST doesn't allowed for custom computed; and where using mobx computed is also too slow.

Fastest way to index on an attribute is to use `observe`, so I'm wondering if anyone has built a `ObservableGroupMap` util for Map to Arrays.

Is there a util in `mobx` or `mobx-utils` that can be similar to this API?

```ts
const cells = observable.map({...});
const cellsByRowId = new ObservableGroupMap(cells, (cell) => cell.rowId)
const cellsByColId = new ObservableGroupMap(cells, (cell) => cell.colId)
```

**Comment by NaridaL** [comment]
What is the key for your map? Could you flip it around by just having an array as a base and having your cells map be another ObservableGroupMap?

**Comment by BrianHung** [comment]
The key for the cell map is id. Can't use an array as the base since we're dependent on map for getting cells by id too.

Is there a performant way of taking an observable map and having a derived observable array of map values that we can use as the base to ObservableGroupMap?

**Comment by NaridaL** [comment]
Can't think of an out-of-the-box of doing this currently. Implementing your own shouldn't be much work though, take a look at https://github.com/mobxjs/mobx-utils/blob/master/src/ObservableGroupMap.ts for inspiration.

**Comment by BrianHung** [comment]
Yah I've managed to make a slight change to `ObservableGroupMap` to support `ObservableMap` as the base input; now I'm just running into a problem mentioned in #284 with `mobx-state-tree`.

**Comment by BrianHung** [comment]
https://gist.github.com/BrianHung/90526784d6f0a403b512ab5a47ce8914

**Comment by BrianHung** [comment]
@NaridaL Closed the issue but would love feedback if you have time, specifically whether to keep enhance or dehanced values in the group arrays. I don't have as experience with mobx as you do ☺️
