### ISSUE TITLE
Invariant failed error when using fromStream in Mobx strict mode.

### ISSUE THREAD

**Issue by reinisriekstins** [mobxjs/mobx-utils#34]
I'm getting the following error:

> Uncaught Error: [mobx] Invariant failed: It is not allowed to create or change state outside an `action` when MobX is in strict mode. Wrap the current method in `action` if this state change is intended

when using the MobxUtils fromStream method in Mobx strict mode. Opting out of strict mode resolves the problem, however I'd strongly like to keep using strict mode.

Here is the callstack:
```
at invariant (mobx.js:2674)
    at checkIfStateModificationsAreAllowed (mobx.js:929)
    at ObservableValue.prepareNewValue (mobx.js:2447)
    at setPropertyValue (mobx.js:2368)
    at StreamListener.set [as current] (mobx.js:2336)
    at new StreamListener (observable-stream.js:56)
    at fromStream (observable-stream.js:105)
    at exports.default (store.js:68)
    at Object.<anonymous> (index.js:15)
    at __webpack_require__ (bootstrap cbf2afa…:555)
```

My code from store.js that might be relevant:
```
    // all the rows selected by the user
  const selected = observable([])

  const
    source$ = Observable
      .from(toStream(() => selected.slice())),
    firstSelected$ = source$
      .first()
      .map(x => x[0]),
    nextToggleSelected$ = source$
      .pairwise()
      .map(([prev, curr]) => {
        if (prev.length < curr.length)
          return last(curr)
        return difference(prev, curr)[0]
      }),
    lastToggleSelected$ = Observable.merge(
      firstSelected$, nextToggleSelected$
    )

  const lastToggleSelected = fromStream(lastToggleSelected$)
```

The last line in that sample is the one from which the error is thrown. The parts `at new StreamListener (observable-stream.js:56)` and `at fromStream (observable-stream.js:105)` from the transpiled mobx-utils correspond to line 72 `this.current = initialValue;` and line 81 `        this.current = value;` in the observable-stream.ts source file.
    
Is there any way to fix this without disabling useStrict?

EDIT: Forgot to mention - I tried wrapping fromStream into an action, but it didn't seem to work.

**Comment by mweststrate** [comment]
Thanks for reporting! The issue should be fixed by 1.1.6
