### ISSUE TITLE
asMap deprecation warning with mobx 3.x

### ISSUE THREAD

**Issue by RainerAtSpirit** [mobxjs/mobx-utils#35]
Update: Just saw in the changelog that mobx-utils 2 is already using mobx3.

I'm getting the following in combination with mobx 3:
```mobx.js:2604 [mobx] Deprecated: asMap is deprecated, use observable.map or observable.shallowMap instead```

https://github.com/mobxjs/mobx-utils/blob/b9b35875b25c81073c9483476ebc054f12e13755/src/create-view-model.ts#L15

**Comment by RainerAtSpirit** [comment]
https://github.com/mobxjs/mobx-utils/pull/36

**Comment by mweststrate** [comment]
Released as 2.0.1. Many thanks for the PR!
