### ISSUE TITLE
fromPromise which starts with fulfilled state

### ISSUE THREAD

**Issue by alisabzevari** [mobxjs/mobx-utils#39]
We mostly use `fromPromise` to render loading or other states in react components. Here is a sample component:
``` jsx
@observer
class MyComponent extends React.Component {
  @action componentDidMount() {
    this.entity = this.props.store.getEntity();  // getEntity returns a `IPromiseBasedObservable`
  }

  @observable entity = fromPromise(Promise.resolve());

  render() {
    return this.entity.case({
      fulfilled: value => (<div>{JSON.stringify(value)}</div>),
      rejected: error => (<div>Error</div>),
      pending: () => (<div>Loading entity...</div>)
    });
  }
}
```
I have initialized `entity` with a resolved `fromPromise` to avoid writing an `if` in `render` method. What I think is really useful is `fromPromise(value)`. So `fromPromise` does not necessarily needs a `Thenable` object.

**Comment by mattruby** [comment]
I agree that it would be nice to be able to initialize a `fromPromise` with an arbitrary state.  I've had to add `null` checks in a few places to deal with this issue.

**Comment by alisabzevari** [comment]
I can create a PR for that.

**Comment by jamiewinder** [comment]
Just to add, in some circumstances it can be handy to create a PromiseBasedObservable in a static pending or rejected state too. For example:

```
@computed get data(): IPromiseBasedObservable<Data> {
    const serverData = this.serverData;
    if (serverData.state != REJECTED) {
        return fromPromise.state(serverData.state); // *
    }
    // process local data + server data
}

@computed get serverData(): IPromiseBasedObservable<Data>{
    return fromPromise(fetchServerData);
}
```

**Comment by mweststrate** [comment]
PR's are welcome

**Comment by mweststrate** [comment]
3.0.0 introduced the methods `fromPromise.reject(value)` and `fromPromise.resolve(value)`.
