### ISSUE TITLE
ViewModel Does it support Plain variables 

### ISSUE THREAD

**Issue by kamarajuPrathi** [mobxjs/mobx-utils#42]
Assuming i have i have observables not part of a prototype (model) they are individual attributes as below 

class ExampleStore{
@observable test1
@observable test2
@observable test3

}

i need to do dirty check whether they have changed or not

**Comment by mattruby** [comment]
I'm not sure what you're after.  If you require the ability to dirty check, see https://github.com/mobxjs/mobx-utils#createviewmodel

What are you trying to accomplish?  If you create a fiddle showing your issue, I'll try to look into it for you.
See: https://github.com/mobxjs/mobx-examples for baseline fiddles.

**Comment by kamarajuPrathi** [comment]
@mattruby In createViewModel does it require a model(class) to do the dirty check 
as in the example 
i have one observable field title was under a model(class) Todo . assume that i didnt have Todo class , title was an observable field in the store , will be able to create a viewModel just for title field

**Comment by kamarajuPrathi** [comment]
@mattruby To explain well 
I have a Ui screen , where i have one inputText Field . i just need to dirty check that field .

**Comment by mattruby** [comment]
"The viewmodel proxies all enumerable property of the original model" 
You don't have to use a class, you can pass an object with observable fields just as well.  It will be wrapped.  

I'd put my form data in a separate model and wrap that with `createViewModel`

**Comment by kamarajuPrathi** [comment]
@mattruby can i wrap just an observable field with createViewModel?

**Comment by mattruby** [comment]
I don't think so. I don't think it will work with a boxed observable. It
needs a key to name the field.

**Comment by kamarajuPrathi** [comment]
@mattruby Thank you

**Comment by kamarajuPrathi** [comment]
@mattruby Do you have any examples of using createViewModel in the components

**Comment by mattruby** [comment]
@kamarajuPrathi Nope.  If you'd like me to create one, feel free to open a new issue over at mobx-examples.  If I get some time, I will make one for you.

**Comment by kamarajuPrathi** [comment]
@mattruby Sure  I have opened in the mobx-examples even .Please create one exmaple that would really helpful
