### ISSUE TITLE
lazyObservable does not work with an array as the initial value

### ISSUE THREAD

**Issue by Veikedo** [mobxjs/mobx-utils#44]
This code will cause an error
`myArray = lazyObservable(sink => fetch("/items").then(items => sink(items)), []);`

the error is: 
` TypeError: value.set is not a function`
pointed to this line https://github.com/mobxjs/mobx-utils/blob/master/src/lazy-observable.ts#L54

**Comment by razetdinov** [comment]
This is because `observable(initalValue)` expects a boxed observable and gets an observable array instead.

An ugly workaround:
```javascript
myArray = lazyObservable(
    sink => fetch("/items").then(items => sink(items)),
    observable.box([])
);
```

**Comment by mweststrate** [comment]
Will be fixed in the next release, thanks for reporting!
