### ISSUE TITLE
Concept of readable and writeable References

### ISSUE THREAD

**Issue by hediet** [mobxjs/mobx-utils#46]
## Problem
Lets say I have the following model:
```ts
interface Model {
  firstName: string;
  lastName: string;
}
const model: Model = observable({ firstName: "John", lastName: "Doe" });
```

And the following react component:
```ts
@observer
class MyTextBox extends React.Component<{ ... }, {}> { 
    render() { ... <Input type="text" onChange={this.onTextChange} /> ...  }
    onTextChange() { ... }
}
```

And now I want to have a view that has a `MyTextBox` for `model.firstName` and another one for `model.lastName`.
The default approach would be to to pass to functions to `MyTextBox`:
```ts
<MyTextBox getText={() => model.firstName} setText={val => model.firstName = val;} />
<MyTextBox getText={() => model.lastName} setText={val => model.lastName = val;} />
```
However, this is cumbersome and error prone as `firstName` and `lastName` must be referenced multiple times.

It would be very convenient, if I could just bind `firstName` somehow to the text value of the text box as supported by Microsofts WPF:
```ts
<MyTextBox text={binding(model.firstName)} />
<MyTextBox text={binding(model.lastName)} />
```
Clearly, `binding` can never be implemented in a way that this would work.

## Proposed Solution
Instead of passing a getter and setter, one could combine both to a "reference":
```ts
interface Reference<T> {
    get(): T;
    set(value: T);
}
```

With the help of typescripts recently introduced keyof-feature, it becomes possible to create a reference to a property in a typesafe manner:
```ts
function ref<T, TKey extends keyof T>(obj: T, key: TKey): Reference<T[TKey]> {
    // ...
}
```

Using this function, the example above could be implemented as:
```
<MyTextBox text={ref(model, "firstName")} />
<MyTextBox text={ref(model, "lastName")} />
```
TypeScript checks that the properties `firstName` and `lastName` exist on `model` and that they have the required type of `Reference<string>` (assuming that `text` has this type).
Sadly, TypeScript tooling does not offer completion of the property name.

To overcome that issue, a little bit of black magic could be used to denote the property name:
```ts
<MyTextBox text={ref2(model, m => m.firstName)} />
<MyTextBox text={ref2(model, m => m.lastName)} />
```
With `ref2` being implemented as following (`ref2` could even be an overloading of `ref`):
```ts
function ref2<T, TProperty>(obj: T, memberAccessor: (obj: T) => TProperty): Reference<TProperty> {
    const dummy: { [key: string]: any } = {};
    for (const member in obj)
        dummy[member] = member;
    const key = memberAccessor(dummy as T) as string;
    return ref(obj, key);
}
```

As the concept of references turned out to be very useful in one of my projects and thus might be useful for others too, I think it might be great to have the interfaces `Reference<T>` as well as a `ref`-like function in mobx-utils.
What do you think?

**Comment by mweststrate** [comment]
Note that `observable.box(value)` basically creates a reference you are describing. If you want a reference that simply wraps around an already existing observable property, you can use `computed` and provide it both a getter and setter
