### ISSUE TITLE
fromPromise: Pass initialValue to the pending handler of case method

### ISSUE THREAD

**Issue by quanganhtran** [mobxjs/mobx-utils#53]
The purpose of `initialValue` is to provide a value when the promise final value is not yet available.
From https://github.com/mobxjs/mobx-utils/blob/master/src/from-promise.ts#L50
```js
switch (this.state) {
    case "pending": return handlers.pending && handlers.pending();
    case "rejected": return handlers.rejected && handlers.rejected(this.value);
    case "fulfilled": return handlers.fulfilled && handlers.fulfilled(this.value);
}
```
The way to distinguish between a fulfilled `this.value` and a rejected `this.value` is the promise state. Same applies to a pending `this.value` since the boxed observable has its value set to `initialValue` in the beginning. Therefore I propose that we also pass `this.value` to the pending handler. Since I haven't studied more scenario, please tell me if there is any problem that might arise that I'm unaware of.

Passing `initialValue` to the pending handler in this case eliminates the need of using closure to access the promise value from the handler (good for composability?)

I can attempt a PR if need be

**Comment by mweststrate** [comment]
@quanganhtran PR welcome!

**Comment by mweststrate** [comment]
Removed `initialValue` in 3.0.0 as it is a weird concept in a promise. It is clearer and recommended to use a constant instead.
