### ISSUE TITLE
fromPromise: Shallowly observe a promise

### ISSUE THREAD

**Issue by quanganhtran** [mobxjs/mobx-utils#54]
From https://github.com/mobxjs/mobx-utils/blob/master/src/from-promise.ts#L24
The value of the wrapper is an `observable.box`, which means result of the underlying promise will be made deeply observable

The purpose of `fromPromise` should be observing the state of the promise itself, and not the state of its value (except the reference). Therefore I propose adding an option (or make it the default behavior, but that would be a breaking change?) to shallowly observe the promise using `observable.shallowBox`

**Comment by mweststrate** [comment]
Yes, it should be a shallow box indeed. Feel free to submit a PR

**Comment by mweststrate** [comment]
For the breaking part, probably we should add a parameter that makes it possible to choose between this behavior, and now default it to the behavior as-is

**Comment by mweststrate** [comment]
Fixed and released as 3.0.0
