### ISSUE TITLE
Mobx-utils/fromPromise.state is not Observable?

### ISSUE THREAD

**Issue by Ridermansb** [mobxjs/mobx-utils#56]
I try to react when `state` change.. but looks like `state` is not a observable...

    const result = fromPromise(promise);
    console.assert(isObservable(result.state), 'state is NOT an isObservable'); // AssertionError: state is NOT an isObservable

Full code.. 
https://runkit.com/ridermansb/mobx-react-is-observable/0.0.5

**Comment by urugator** [comment]
```javascript
isObservable(result.state)
// is evaluated to
isObservable("pending"); // value (string) can't be observable
// but:
isObservable(result, "state"); // true
```

**Comment by Ridermansb** [comment]
You are right. Sorry, I didn't see that.

**Comment by Ridermansb** [comment]
Whats I`m missing here... ?

https://runkit.com/ridermansb/mobx-react-is-observable

    isObservable(result, 'state') // false

**Comment by urugator** [comment]
Hm looking at impl, the getters themselfs aren't observable, they just delegate the access to inner observable structures... Sorry for false info. Not sure why it's designed like this...

**Comment by mweststrate** [comment]
Good point, could be marked as `@computed` to fix that. On the other hand, it doesn't change the semantics, as there is an observable backing behind it. So the computed wouldn't do really anything. Do you need it to be explicitly observable @Ridermansb ?
