### ISSUE TITLE
fromPromise.state as properties of fromPromise.status

### ISSUE THREAD

**Issue by cadc** [mobxjs/mobx-utils#58]
it would be cool if you could access the status of a fromPromise as properties instead of accessing the state as strings.
e.g
```
const promise = Promise.resolve()
fromPromise(promise).status.pending && <span>Pending</span>
```
instead of 
```
const promise = Promise.resolve()
fromPromise(promise).state === "pending" && <span>Pending</span>
```
i think it would be a bit easier to spot spelling errors if there was an error thrown.
you could do something similar with case but its still not quite as nice
```
const promise = Promise.resolve()
promise && fromPromise(promise).case({pending: () => <span>Pending</span>})
```
thoughts?

**Comment by mweststrate** [comment]
I think it is weird to have three mutually exclusive properties reflecting the same state. Besides that, I think two ways to inspect the state is already more then enough, let's not make it confusing by adding a third one. Note that for "pending" and such, those are exposed as constants from the module, so you don't have
 to use strings. `import { PENDING } from "mobx-utils"` etc.
