### ISSUE TITLE
IPromiseBasedObservable-s don't respect transactions

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx-utils#61]
This is probably best explained by example:
https://codesandbox.io/s/L88MnpzRX

(see console)

Basically I have four observables - `a` and `b` are `fromPromise` IPromiseBasedObservable-s, and `c` and `d` are just boxed values. The autorun displays their values. 

I change `c` and `d` within a `runInAction` and as expected the autorun runs once.
I change `a` and `b` within a `runInAction` and *not* as expected the autorun runs twice - once for each. 

Expected output:
```
?, ?, c , d
?, ?, C , D
A, B, C , D
```
Actual output:
```
?, ?, c , d
?, ?, C , D
A, ?, C , D
A, B, C , D
```

I **think** this is just an inevitable side-effect of using promises, but I thought I'd raise it.

**Comment by urugator** [comment]
> I change a and b within a runInAction

But you don't. You just resolve the original Promise, but that Promise doesn't modify the `a` or `b`. 
A new Promise is created [here](https://github.com/mobxjs/mobx-utils/blob/master/src/from-promise.ts#L25), which is the one which actually modifies `a` or `b`. The `resolve` function of this new Promise is deffered and runs after the `runInAction` ends (outside of action).

It is not possible to modify `a` or `b` externally (other than `p._state.set(val)`), therefore it doesn't make sense to talk about some relation to transactions...
