### ISSUE TITLE
Feature Request: whenAsync

### ISSUE THREAD

**Issue by daedalus28** [mobxjs/mobx-utils#66]
I have a few use cases where I'd like a promise for when an observable is set with a certain value. `when` is awesome, but it effectively takes a callback for when the predicate returns true instead of resolving a promise.

I've implemented this as `whenAsync` like so:

```js
let whenAsync = fn => new Promise(resolve => when(fn, resolve))
```

And I use it like this:

```js
await whenAsync(() => !state.someBoolean)
```

It's especially useful for detecting when boolean values change, e.g. getting a promise for when a modal closes, something finishes loading, etc. It's also useful for testing. We have utils here to convert from a promise to an observable, but not the other way around.

Would something like this be useful as a pull request?

**Comment by mweststrate** [comment]
Yes makes perfect sense!

Op vr 28 jul. 2017 00:45 schreef Samuel Greene <notifications@github.com>:

**Comment by daedalus28** [comment]
Awesome, I'll add a PR for it!

**Comment by daedalus28** [comment]
Hi there! I've taken a quick stab at a PR adding `whenAsync`. I tried to follow conventions used by the project already but I'm sure I'm missing things. Feedback is greatly appreciated 😄

**Comment by daedalus28** [comment]
@mweststrate Any update on this? I've had a PR open for a while
