### ISSUE TITLE
README \@

### ISSUE THREAD

**Issue by d4rky-pl** [mobxjs/mobx-utils#69]
Hey, I've noticed that all README examples prefix `@decorators` with `\`. Is it a TypeScript, did I miss something or is it just a typo and I should send a PR? :)

**Comment by mweststrate** [comment]
No, truth is, I don't know how to write decorators in JSDoc comments. `@xx` is parsed as JSDoc instruction so `@observable`  would close the `@example` block. If you know how to fix it, PR is welcome :-D

**Comment by d4rky-pl** [comment]
Seems like a bug in Doctrine, the parser that documentation uses - eslint/doctrine#188
