### ISSUE TITLE
introduce `guard` (or `invariant`)

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-utils#7]
``` javascript
function guard(expr) {
   return autorun(() => {
     if (!expr) throw "Inviariant violated!"
   })
}
```

```
guard(() => car.isSpeeding === car.speed > 120)

guard(() => cache.size() === data.length)

// etc
```

**Comment by drslump** [comment]
:+1: given the intended usage, the error could even be generated with something like:

```js
function guard(expr) {
  return autorun(() => {
    if (!expr()) {
      throw `Invariant violated! ${ expr.toString().replace(/^(\(\s*\)\s*=>\s*)?/, '') }`
  }
}
```

Any idea of how disable the *guards* for optimized production builds? I guess a *noop* could be injected with a build tool (ie: webpack) but I guess it'll also be nice if the guards could be disabled at runtime.
