### ISSUE TITLE
@asyncAction with ES6 (not TypeScript)

### ISSUE THREAD

**Issue by d4rky-pl** [mobxjs/mobx-utils#70]
[It seems that generator functions do not work with decorators](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/issues/26).

~I've tried using `@asynAction something = function*() {}` but it does not seem to work properly.~

The easiest workaround so far seems to be:

```javascript
class Foo {
  fetch = asyncAction(function* fetch() {
    // ... code ...
  })
}
```

It might be a good idea to add this to README :) I can send a PR if you agree.

**Comment by mweststrate** [comment]
@d4rky-pl agreed :)

**Comment by jshaker** [comment]
Why not just call a regular action within an async function?

**Comment by d4rky-pl** [comment]
@mweststrate This will take a bit longer, I'm afraid. The comments in code are not always valid JSDOC so every time documentation is regenerated, there are some things missing, some broken etc. I will dig into it when I have more spare time :)
