### ISSUE TITLE
Get values from view modal?

### ISSUE THREAD

**Issue by minipai** [mobxjs/mobx-utils#72]
Hi, do you think it's reasonable to add a method to viewModal to get current values? 
Now I end up using  `var { localValues, model, isPropertyDirty, ...data } = viewModal`
and use the `data`
I am happy to add it and make PR.

**Comment by mweststrate** [comment]
Feel free to create such a thing :) `getCurrentState()` ?

**Comment by ItamarShDev** [comment]
Isnt current values sits in the `model` prop?
Am I missing something?

**Comment by minipai** [comment]
Sorry, I am not using viewModal any more after using Formik.
