### ISSUE TITLE
best way to use the lib

### ISSUE THREAD

**Issue by geohuz** [mobxjs/mobx-utils#73]
I'm not sure if the fromPromise object can be mutated directly or I need to use set function? The same question applies to the createViewModal, it seems that we can mutate viewModal directly without having set function. And can we createViewModal from fromPromise? Thanks!

**Comment by urugator** [comment]
> fromPromise object can be mutated directly or I need to use set function

Object returned from `fromPromise` is read only.

>  it seems that we can mutate viewModal directly without having set function

You can modify viewModel just like the object it was created from.

> can we createViewModal from fromPromise

Haven't tried, maybe possible, but quite useless to do so I think.
