### ISSUE TITLE
Computed Async

### ISSUE THREAD

**Issue by jshaker** [mobxjs/mobx-utils#76]
I don't know if this has been brought up before, I'd assume so, but is there any plans to release a ComputedAsync in mobx-utils? 

Here it's been developed by a 3rd party: https://github.com/danielearwicker/computed-async-mobx

I personally enjoy this plugin and so far it hasn't failed me. Of course I'd prefer using features that are supported by the MobX community and so maybe there's a reason why the use of ComputedAsync is not a good option.

I know I can achieve the same results of a ComputedAsync with either the fromPromise utils or even just using autorun, but I find it makes the code less readable and intuitive as a ComputedAsync does.

**Comment by mweststrate** [comment]
Yep that looks pretty need! If @danielearwicker is interested in merge it, PR's are welcome :) 

That being said, Daniel is not unknown in the MobX communty, so I think you can safely use his work even if not part of mobx-utils ;-)

**Comment by danielearwicker** [comment]
I just last week rewrote it to be a ultra thin layer over `fromPromise`, so I will gladly PR it into -utils. My tests are a shameful mess though, lots of timing dependent async crap. So I will tidy that up first.
