### ISSUE TITLE
how do I use fromStream with mobx-react observer?

### ISSUE THREAD

**Issue by devdoomari** [mobxjs/mobx-utils#77]
in TS, when I do:

```
const someSignal = fromStream(someStream);
```

I only get someSignal of type:
```
{
   current: {},
   dispose: () => ...
}
```
which ...doesn't seem like a mobx observable.
Is there an example of using fromStream with mobx-react's observer?

Thank you!

**Comment by mweststrate** [comment]
the `current` method is tracked, so if you use it you get updated when it
updates in the future. See also the unit-tests

Op vr 1 sep. 2017 om 09:27 schreef devdoomari <notifications@github.com>:

**Comment by devdoomari** [comment]
@mweststrate 
is this the right unit-test file?
https://github.com/mobxjs/mobx-utils/blob/master/test/observable-stream.js
it doesn't seem to give any example of using mobx-react's ```@observer``` and fromStream...
Also, since I'm using typescript, I don't know what to make of fromStream's return type :(

**Comment by mweststrate** [comment]
`.current()` is an observable, so you can just use it in the `render` of an
observer component and it will react to future updates. Mobx utils is
written in typescript, so type inference should be correct.

Op ma 4 sep. 2017 om 10:12 schreef devdoomari <notifications@github.com>:

**Comment by devdoomari** [comment]
uh... could you post a specific example code?
I'm not that smart enough to understand & implement that on my code...

so far, are you saying ( * I might understand things wrong *):

```
@observable // from mobx-react
class SomeComponent extends React.Component<{ ... }, { ... }> {
    render() {
       const signalValue = this.props.someSignal.current();
       return ( <p> {signalValue} </p> );
   }
}
```

will do? (and that SomeComponent will auto-rerender whenever someSignal is updated?)

**Comment by mweststrate** [comment]
yes that is correct

Op ma 4 sep. 2017 om 10:29 schreef devdoomari <notifications@github.com>:

**Comment by mweststrate** [comment]
but use @observer instead of @observable

Op ma 4 sep. 2017 om 10:33 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by devdoomari** [comment]
ok! thanks for your guidance! closing!

ps: do you think this should be added to mobx-util docs? (or example)?
for someone like me, this might not be very obvious
