### ISSUE TITLE
fromPromise initialValue from previous fromPromise

### ISSUE THREAD

**Issue by xrado** [mobxjs/mobx-utils#9]
Hi

I'm trying to reuse fromPromise value for next fromPromise with initalValue, so the value wont be reset between calls and I'm getting this error "Uncaught TypeError: this._observable.get is not a function". I've looked in to the source but don't know exactly why

```
class Store {
	@observable data = fromPromise(Promise.resolve({}));
	@action getData(){
		this.data = fromPromise(somePromise(),this.data.value);
	}
}
```

first getData call works fine, but the second one throws an Error
Any suggestions?
Thanks for awesome lib!

**Comment by mweststrate** [comment]
If think the above pattern is probably not what you want, as `this.data.value`might not have been reseolved yet, probably you need:

`this.data = fromPromise(this.data.promise.then(() => somePromise()))` ?

**Comment by xrado** [comment]
But that will not set the value until somePromise resolves. It will reset to undefined, right? I would like to keep the the previous data.value when calling getData again and update with new value when promise resolves, so only data.state will change in between.

**Comment by mweststrate** [comment]
In that case just store the value you want to keep in another observable, returning that until the promise resolves? e.g. simply do:

```
@action getData() {
  somePromise().then(data => this.data = data)
}
```

**Comment by xrado** [comment]
yes thats how looked my first implementation
```
getData(){
    this.setState({data:{data:[],isLoading:true}})
    somePromise().then(data => {
         this.setState({data:{data,isLoading:false}})
    })
}
```
I thought fromPromise would come handy because it also holds state of the promise, anyway thanks for the suggestions
