### ISSUE TITLE
toStream does not seems to handle errors

### ISSUE THREAD

**Issue by ArielGueta** [mobxjs/mobx-utils#91]
The `toStream` implementation does not implement error handling. There is no `observer.error()` call to propagate the error. 

```
unsubscribe: computedValue.observe(
                    typeof observer === "function"
                        ? ( {newValue}: { newValue: T } ) => observer(newValue)
                        : ( {newValue}: { newValue: T } ) => observer.next(newValue)
                )
```

**Comment by mweststrate** [comment]
@ArielGueta that is because errors of a computedValue cannot be observed. Rather, they are thrown back to the causer.
