### ISSUE TITLE
Mobx react utils?

### ISSUE THREAD

**Issue by daedalus28** [mobxjs/mobx-utils#93]
Hi there!

We have some utils we built for mobx react that probably don't belong here. Should we create a new repo for `mobx-react-utils`?

As an example, we have a util that wraps observer + inject + displayName. I'm planning to write up something more about this pattern, but it looks like this:

```js
export let Component = (init, render, displayName) => {
  let c = observer(render)
  if (displayName) {
    c.displayName = displayName
  }
  return inject(init)(c)
}
```

In a nutshell, since `inject` creates subscriptions to observables created in it, it allows a really clean functional style api which allows you to have state without creating classes. It's basically a direct answer to https://github.com/mobxjs/mobx-react/issues/69, but also accounts for `displayName` so mobx components look nice in react dev tools.

```js
Component(
  () => observable({someValue: true}),
  props => (
    <div>
      {props.someValue && 'Conditionally Visible Text'}
      <button onClick={() => (props.someValue = !props.someValue)}>Flip</button>
    </div>
  ),
  'ConditionalTextToggler'
)
```

I'd also love to hear if you have any suggestions for the API.

**Comment by mweststrate** [comment]
I think a separate repo would be best indeed! Cool ideas :)
