### ISSUE TITLE
 mobx.observable.map is not a function

### ISSUE THREAD

**Issue by bellostom** [mobxjs/mobx-utils#94]
Hi

Using mobx v2.7, mobx-utils v.3.2.1
I try to wrap an observable in a viewModel by calling createViewModel and passing the observable,
I get the below error
TypeError: mobx.observable.map is not a function
    at new ViewModel (mobx-utils.umd.js:447)
    at createViewModel (mobx-utils.umd.js:560)

Any ideas?

**Comment by bellostom** [comment]
Any comments on this?

**Comment by mweststrate** [comment]
You need mobx 3 or higher: https://github.com/mobxjs/mobx-utils/blob/master/package.json#L52

**Comment by bellostom** [comment]
Thanks
