### ISSUE TITLE
TSLint rules specific to mobx?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mobxjs/mobx-utils#96]
I was reading through https://mobx.js.org/best/actions.html and thought it very interesting that `async` methods need to have special handling beyond just a standard `@action` decorator.

Is there a TSLint rule published anywhere that can enforce `@asyncAction` be used on a generator instead of `@action` on an `async` method?

Scoping out: is there a collection of MobX-specific TSLint rules the way [tslint-react](https://github.com/palantir/tslint-react) exists? If not, I'm willing to take responsibility for making one (my team at work needs such a thing).

Edit: Talked to someone who uses MobX much more than me (@JFrei86). Perhaps an option to ban `async` actions altogether in favor of more granular operations?

**Comment by mweststrate** [comment]
@JoshuaKGoldberg afaik nothing like that exists, but feel free to create such rules :). The only related concept is the [mobx-deep-action](https://github.com/mobxjs/babel-plugin-mobx-deep-action) transformer for babel that wraps async pieces in action.

**Comment by eranshabi** [comment]
I created some rules for MobX and TSLint. Feel free to use (or contribute your own rules): https://github.com/eranshabi/tslint-mobx
